export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGOIRES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGOIRES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGOIRES_FAILED: "category/FETCH_CATEGORIES_FAILED",
  FETCH_DIRECTORY_START: "category/FETCH_DIRECTORY_START",
  FETCH_DIRECTORY_SUCCESS: "category/FETCH_DIRECTORY_SUCCESS",
  FETCH_DIRECTORY_FAILED: "category/FETCH_DIRECTORY_FAILED",
}